### ISSUE TITLE
V9.11 edit not working

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#1]
Upgrade from 8->9 of existing installation:
edit of records is not working
Fatal error: Call to undefined method CobaltModelTfields::getFieldTypeId() in /components/com_cobalt/fields/parent/parent.php on line 30

**Comment by Serhioromano** [comment]
Please download relation fields and close if solved.

**Comment by kiranetph** [comment]
hmmm ... where do i download it?

**Comment by Serhioromano** [comment]
In releases. Open repository home and the click [releases](https://github.com/Serhioromano/cobalt-9/releases) link
