### ISSUE TITLE
Configuration - Folder Format

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#10]
I miss an additional folder format: "YYYY/MM/DD".

In general there should also some info/instructions that if you change the folder format if you have already uploaded data, you will loose access to existing files if the existing folder structure is not updated manually. 
A SQL tool could also fix the fullpath in "fields" of #__js_res_record.

Moving the folder format to the upload field might be another option. So every upload folder could have its individual format. If 2 upload fields use same destination folder, they need to have same folder format.

**Comment by Serhioromano** [comment]
> In general there should also some info/instructions that if you change the folder format if you have already uploaded data, you will loose access to existing files if the existing folder structure is not updated manually. 

But that is not true. Files uploaded with old settings will be accessible by old path.

> A SQL tool could also fix the fullpath in "fields" of #__js_res_record.

That is why we do not need to fix. Old files might be in old locations. But if you want to move all files or better say restructure old files according to new parameter that tool might be needed.

> I miss an additional folder format: "YYYY/MM/DD".

I wonder if I just add this format will it work? I'll try.

**Comment by kiranetph** [comment]
@Serhioromano 

> But that is not true. Files uploaded with old settings will be accessible by old path.

Disagree. Once you update a record, the path will be updated based on the field parameters/config path. So you will lose the connection to the files (at least that is what i remember... i can check). If i don't move files to the new folder structure before i activate the new path settings and update the record it will be gone (until the path of storage is manually fixed/updated)

**Comment by Serhioromano** [comment]
> Once you update a record, the path will be updated based on the field parameters/config path. So you will lose the connection to the files (at least that is what i remember... i can check).

Did you check that?

**Comment by kiranetph** [comment]
I believe yes ... some time ago .. but i will do it again.
Will be out for ~ 2 hours, then i will do some checking.

**Comment by Serhioromano** [comment]
YYYY/MM/DD will create nested folders. I created it and tested it. When you change folder format, old files work fine. Because I use a saved path to file and not generate it every time to show or download.

**Comment by kiranetph** [comment]
YYY/MM/DD folder structure would be preferred if you upload a lot of documents on a daily basis.
Especially for backup or synchronisation. you know my use-case and under the YYY-MM-DD I have now around 1500 folders (with ~450K files)

The column "fullpath" under _js_res_files holds the ful lpath to the files, but is a redundant column anyway, which can be build through "filename" and the date part of "ctime".

Maybe the "fullpath" column is not needed and can be dropped. This will dramatically reduce the size of ##_js_res_files (almost half of the size)

**Comment by Serhioromano** [comment]
> YYY/MM/DD folder structure would be preferred if you upload a lot of documents on a daily basis.

I added this and `YYYY/MM` too

> Maybe the "fullpath" column is not needed and can be dropped. This will dramatically reduce the size of ##_js_res_files (almost half of the size)

Full path is what makes this magic work when you change folder structure in the middle of the work. Even in one article half files are old structure and half new. 

But the file name might be stripped from there. But this will require quite a refactor. One of those changes when after that you are not sure where a bug will come out.
