### ISSUE TITLE
[9.27/57] Installation warnings

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#100]
Installing the pkg_cobalt.j3.everything.v.9.57.zip under a new Joomla 3.9.11 / Php 7.1.30 / 5.5.5-10.4.6-MariaDB gives following install warnings:

Warning : simplexml_load_file(): /cobalt9/tmp/install_5d64eedde996f/package/install_5d64eee089fd0/playthru/playthru.xml:21: parser error : Opening and ending tag mismatch: description line 11 and extension in /cobalt9/libraries/src/Installer/InstallerHelper.php on line 262 Warning : simplexml_load_file(): </extension> in /cobalt9/libraries/src/Installer/InstallerHelper.php on line 262 Warning : simplexml_load_file(): ^ in /cobalt9/libraries/src/Installer/InstallerHelper.php on line 262 Warning : simplexml_load_file(): /cobalt9/tmp/install_5d64eedde996f/package/install_5d64eee089fd0/playthru/playthru.xml:22: parser error : Premature end of data in tag extension line 2 in /cobalt9/libraries/src/Installer/InstallerHelper.php on line 262 Warning : simplexml_load_file(): in /cobalt9/libraries/src/Installer/InstallerHelper.php on line 262 Warning : simplexml_load_file(): ^ in /cobalt9/libraries/src/Installer/InstallerHelper.php on line 262 {"success":false,"message":null,"messages":{"warning":["JInstaller: :Install: Can't find Joomla XML setup file.","Install path does not exist.","Package Install: There was an error installing an extension: plg_cobalt.captcha.playthru.j3.v.1.2.zip"],"error":["Error installing package"]},"data":{"redirect":"\/administrator\/index.php?option=com_installer&view=install"}}

![image](https://user-images.githubusercontent.com/15226809/63756401-e1efc380-c8ea-11e9-8e1c-fe7f6088cc3f.png)

**Comment by Serhioromano** [comment]
Fixed will update release in few moments
