### ISSUE TITLE
В процессе установки произошла ошибка.

### ISSUE THREAD

**Issue by pavel8289** [Serhioromano/cobalt-9#101]
При установки pkg_cobalt.j3.everything.v.9.57 вылезла ошибка 

> JInstaller: :Install: Не найден установочный XML-файл Joomla
> Путь установки не существует
> Пакет Обновить: В процессе установки произошла ошибка: 
> plg_cobalt.captcha.playthru.j3.v.1.2.zip

Joomla 3.9.11

**Comment by kiranetph** [comment]
Duplicate of #100

**Comment by Serhioromano** [comment]
Got o releases and grub latest 

https://github.com/Serhioromano/cobalt-9/releases
