### ISSUE TITLE
[9.27/57] Configuration - Missing user warning

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#102]
![image](https://user-images.githubusercontent.com/15226809/63756921-cb963780-c8eb-11e9-8a33-7ca54ba50371.png)

It seems there is still a reference to a User ID 745

**Comment by kiranetph** [comment]
The default for the Global Moderator should be the Super User from the Joomla installation to avoid an error message.

**Comment by Serhioromano** [comment]
Fixed
