### ISSUE TITLE
[9.27/57] Installation - Automatic creation of Menu item "Admin Dashboard"

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#103]
To avoid confusion and help new users to start working with Cobalt 9, the installer should already create a menu item to the Admin Dashboard / Control Panel.
It will definitely reduce support questions how to start with Cobalt 9.

The existing control Panel / Dashboard still looks quite outdated. 

See also issue #42 Quick Start Mode

**Comment by Serhioromano** [comment]
I'll add link creation, and about look, I'll work on look after I finish all functionality. I definitely what fresh look for Cobalt.

**Comment by Serhioromano** [comment]
https://github.com/Serhioromano/cobalt-9/releases/tag/9.65

New release. Try install this one.

**Comment by kiranetph** [comment]
[9.65] installs without error/warnings.

No menu item was yet created. 

I will reopen the issue until the link creation / menu creation of the frontend access to the Admin Control Panel is included/working so that the issue will not be forgotten.

**Comment by Serhioromano** [comment]
I am working on a menu item. Not only menu item I'll assign the current user as global admin and set uploads folder. So after install can be used immediately. Without warnings.

**Comment by Serhioromano** [comment]
9.70 now includes that.

**Comment by kiranetph** [comment]
Actually it creates the menu link under the Access Group: "Special". Most probably no user is assigned to it.
I would suggest to assign the menu link to Access Group "Super User" (admin), since this user might be the one to configure/start working with Cobalt 9 at the frontend and most probably it was the one who installed Cobalt 9 at the back-end.

**Comment by Serhioromano** [comment]
I thought the superuser will see links for special. Will he?

**Comment by Serhioromano** [comment]
I've changed to Super User.

**Comment by kiranetph** [comment]
super user can not see special .. when I tried it, it did not show the link ...
