### ISSUE TITLE
error when adding new field

### ISSUE THREAD

**Issue by mekamak** [Serhioromano/cobalt-9#107]
error when adding new field
 PHP regular expression limit reached (pcre.backtrack_limit)

**Comment by kiranetph** [comment]
Can't recreate the error.
Please specify the C9 version and field type

**Comment by mekamak** [comment]
Cobalt 9
add new field screen never opens
http://www.e-mehmet.com/video/hata.webm

**Comment by Serhioromano** [comment]
Looks like your SEF plugin.

**Comment by kiranetph** [comment]
At this early stage, I would suggest to test the C9 BETA only with a fresh Joomla installation without additional plugins, templates and modules to concentrate on compatibility with Joomla first.

**Comment by mekamak** [comment]
no add-ons. test setup already. joomla 3.9.11

**Comment by Serhioromano** [comment]
I cannot reproduce even with SEF on. Do you have 3d party SEF extension? The trace obviously show that error is in file plugins/sef/sef.php
