### ISSUE TITLE
Create New Field - Cancel button doesn't work

### ISSUE THREAD

**Issue by danielbidala** [Serhioromano/cobalt-9#11]
Console log:
Uncaught TypeError: Cannot read property 'firstChild' of nullJoomla.removeMessages @ core-uncompressed.js:198Joomla.renderMessages @ core-uncompressed.js:151isValid @ validate-uncompressed.js:128Joomla.submitbutton @ index.php?option=com_cobalt&view=tfield&type_id=1&layout=edit:466onclick @ index.php?option=com_cobalt&view=tfield&type_id=1&layout=edit:503

**Comment by Serhioromano** [comment]
I would like to have access to this one. because that might be a lot of things. Cannot reproduce locally.
