### ISSUE TITLE
[9.71] Dashboard - Records link

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#112]
Records link is not working with a clean installation of Cobalt 9.71

![image](https://user-images.githubusercontent.com/15226809/63945422-de546c00-caa5-11e9-9e61-377dfca1f315.png)

**Comment by Serhioromano** [comment]
I've added ip2country back to release to download. I have to make that require. The problem is that if I add it to pack it will exceed 2mb. Although nowadays that might be a not as big problem already.

**Comment by kiranetph** [comment]
Don't mind the 2MB file size anymore .. popular extensions like akeeba backup (~2.9MB) are all over 2MB. Don't limit yourself in trying to stay within the "limit"

**Comment by Serhioromano** [comment]
Then I could include media pack into a package. So it is a single pack. I also think Joomla uses chunk upload. So size should not matter. Next release I'll make a single pack.

**Comment by mekamak** [comment]
9.75 is beautiful.
My hosting cobalt9 is also a problem.
No local problems.

**Comment by Serhioromano** [comment]
@mekamak  
>My hosting cobalt9 is also a problem.

Tell me all your problems.
