### ISSUE TITLE
[9.71] Dashboard - Quick Start - missing navbar

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#113]
under Quick start, the navbar on top does not show

**Comment by Serhioromano** [comment]
Navbar is hidden in all forms. Edit section, type, field, .... It is kinds like disable menu in the backend when editing. Does it make sense?

**Comment by kiranetph** [comment]
Somehow ... ok

**Comment by Serhioromano** [comment]
Ok what? ok like this or add navbar? This is one line of code, it is a matter of reasoning.

**Comment by kiranetph** [comment]
lets just leave it as it is and see later when it is in action with different templates ...

**Comment by Serhioromano** [comment]
I added navbar there, I think that on the point of quick start for beginners we have to give then a way to go.
