### ISSUE TITLE
Caution when starting cobalt 9 configuration.

### ISSUE THREAD

**Issue by mekamak** [Serhioromano/cobalt-9#114]
Caution when starting cobalt 9 configuration.
Apache mod_rewrite should not be opened.
pkg_cobalt.ip2country.v.8.0  required to be installed.
Alert required.

**Comment by Serhioromano** [comment]
Next release ip db will be in the package as well as mediapack. But what about mod_rewrite? I cannot get is it yur suggestion or is it what you see as a message?

**Comment by mekamak** [comment]
If mod_revrite is turned on in the first configuration, adding fields is a problem.

**Comment by kiranetph** [comment]
What do you mean exactly with first configuration?

Running here Apache/2.4.41 (Unix) OpenSSL/1.0.2s PHP/7.1.30 with mod_rewrite loaded and I can add field under TYPE and don't experience problems under configuration.

**Comment by kiranetph** [comment]
Try to use the new "Quick Start" function at the control panel to get a working TYPE with 2 fields.

**Comment by mekamak** [comment]
I found the solution. I have no problem. Thanks.

**Comment by Serhioromano** [comment]
@mekamak Could you please explain what was the problem? Is there anything on our side to make to avoid the same problems in the future?
