### ISSUE TITLE
[9.73] upload - problem with library selector

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#115]
in [9.71] you could select between "moo tools" and "flow" library. Now there is only a text field. 
![image](https://user-images.githubusercontent.com/15226809/64022512-05c03d00-cb69-11e9-8aca-e366c9c45649.png)

**Comment by Serhioromano** [comment]
Cannot reproduce. try this one.

[pkg_cobalt.j3.everything.v.9.74.zip](https://github.com/Serhioromano/cobalt-9/files/3560611/pkg_cobalt.j3.everything.v.9.74.zip)

**Comment by Serhioromano** [comment]
Oppc. The pack did not update, forgot to commit. Get this one!

[pkg_cobalt.j3.everything.v.9.75.zip](https://github.com/Serhioromano/cobalt-9/files/3560629/pkg_cobalt.j3.everything.v.9.75.zip)

**Comment by Serhioromano** [comment]
Fixed. Now it only works after a field was saved.
