### ISSUE TITLE
[9.73] upload - select default file

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#116]
As discussed several times on Cobalt 8 Forum, it would be good to have a "default" file out of the uploaded files.
If several files were uploaded, 1 can be marked as the default.

**Comment by Serhioromano** [comment]
Working on this one. Do not forget parameter for every field.

**Comment by Serhioromano** [comment]
I wonder what role this feature would play in uploads field for example? I understand in the gallery to select default image to show in the list. But in uploads? I cannot see practical application.

**Comment by kiranetph** [comment]
In general to select a "default" file.
Example:
A record of a person gets every month a new document. Maybe an evaluation. Or a yearly exam sheet... 
When we start the record, there might be already a collection of documents. To determine the latest.

**Comment by Serhioromano** [comment]
DOne.
