### ISSUE TITLE
[9.78] upload field - flow folder upload progress bar not complete

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#120]
The folder upload progress bar is confusing. It looks like it was not uploaded properly.

![2019-09-02_14-32-51](https://user-images.githubusercontent.com/15226809/64094575-cbd08000-cd8e-11e9-8600-b275e4f663ef.png)

On the flow.js demo site, it shows complete progress bars for folder upload

![image](https://user-images.githubusercontent.com/15226809/64094634-ec003f00-cd8e-11e9-9575-7e66e8d2e58f.png)

**Comment by Serhioromano** [comment]
Fixed. 

Later I'll make that upload for gallery field.
