### ISSUE TITLE
[9.78] upload workflow improvement

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#123]
For the flow upload:
Based on experience from daily use with encoders, sometimes after successful upload of a file the users exit the record form without saving it.

I would propose following workflow:
If you upload file(s), save(apply) the record immediately after successful upload  

If it is a new record, "cancel" should act like "delete" if the new record was already saved.

**Comment by Serhioromano** [comment]
Since new record cancel is deleted then the user has to save the first record anyway. So that may stay untouched. 

I made it so that if article is saved and you upload file, you do not need to save article.
