### ISSUE TITLE
[9.78] upload flow - description indicator

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#124]
It would be good to have a description indicator in the upload list, when a file has an encoded description.

Example:
The first 2 files have a description. but we can not see it. 
![image](https://user-images.githubusercontent.com/15226809/64101923-7782cb80-cda1-11e9-8cee-091435be8aab.png)

**Comment by Serhioromano** [comment]
this was a hard one. Very unstable. I found some vulnerability if in description to place quotes, it stops working. I've fixed it but the question remains. Should I clean those values or not.
