### ISSUE TITLE
[9.78] upload flow - description - revised workflow

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#125]
If you enter a description through the modal window and "save" it, is not yet saved with the record.
![image](https://user-images.githubusercontent.com/15226809/64102345-566eaa80-cda2-11e9-9822-97b9762fdd0b.png)

Actually, you have to "apply" or save the record first before you can even enter the description. 
Even if you "save" the modal window and want to edit the same description again, you can not see it. (only after "save" or "apply" the record again.

Better workflow in combination with #123 :
When you upload a file, the record will be saved automatically so that the description icon shows up.
When pressing the description icon, the modal window will open and the description is saved to the database when closing the modal window.
An alternative: when clicking the description icon, a 2nd line with the entry field will open below and content is saved via AJAX

**Comment by Serhioromano** [comment]
> Actually, you have to "apply" or save the record first before you can even enter the description.

Unfortunately, this is not solvable very simply. This feature depends on record_id and saved file ID. So it is hard, but I'll see what I can do. 

> When you upload a file, the record will be saved automatically

This is also not an easy task. A user might be in the half of the required fields entered and the article might be not ready to be saved. To make Safe Draft feature and save articles with draft status without checking and validating, is a whole new world!

> An alternative: when clicking the description icon, a 2nd line with the entry field will open below and content is saved via AJAX

That is how it works how. AJAX saves data.

**Comment by Serhioromano** [comment]
Looks like I've solved everything
