### ISSUE TITLE
[9.78] packer - different warnings

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#126]
Notice: Undefined variable: li_out in /cobalt9/components/com_cobalt/models/packsection.php on line 139

Warning: implode(): Invalid arguments passed in /cobalt9/components/com_cobalt/models/packsection.php on line 139

Notice: Undefined variable: divs in /cobalt9/components/com_cobalt/models/packsection.php on line 142

Warning: implode(): Invalid arguments passed in /cobalt9/components/com_cobalt/models/packsection.php on line 142

**Comment by Serhioromano** [comment]
Fixed but looks like you try to pack section where type is not selected.
