### ISSUE TITLE
[9.78] upload - combined drop / upload file area 

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#129]
Right now, a drop area and a file selector are used side by side:

![image](https://user-images.githubusercontent.com/15226809/64170723-614d3c00-ce83-11e9-889a-132f5b878514.png)

An **additional option** (default) would be a combined area similar to this:

![image](https://user-images.githubusercontent.com/15226809/64170753-80e46480-ce83-11e9-9903-0403f4446b82.png)

(sample from Dropzone.js)

looks more "professional" in my opinion.

**Comment by Serhioromano** [comment]
That would be an ideal solution. But we can only afford optimal solution. I have 3 types of buttons

- Open file
- Open folder
- Open images

It will be hard to combine it in one single drop area. 

Although I can place buttons as links inside drop area.

> Drop your files here or upload a _file_ or a _folder_

Whee file and folder are links like buttons to open the file browser.

I'll keep this in mind when I refactor all looks of all Cobalt to new styles.
