### ISSUE TITLE
Conditional parameter

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#13]
Section/Type/Field/Template parameter should have a "conditional" functionality to make it easier and less confusing/intimidating for starter.
A good example is the TYPE parameter "Rating":
![rating](https://cloud.githubusercontent.com/assets/15226809/12255240/7de3f964-b92c-11e5-8101-eefd5efbdd96.jpg)

If parameter "Who can rate" = "No One" it should not display any other option -->
![rating2](https://cloud.githubusercontent.com/assets/15226809/12255282/f06f7436-b92c-11e5-8936-2b7bdeee019c.jpg)

Similar to the multirating: if "Enable multiple rating" is "No" don't show the options

![rating3](https://cloud.githubusercontent.com/assets/15226809/12255331/7d1f72dc-b92d-11e5-9d5c-4a3a8930349d.jpg)
- [ ] Section
- [ ] Type

**Comment by Serhioromano** [comment]
That would be really neat feature. But unfortunately we render this based on XML. Technically it is not easy. But I'll see what I can do. I'll give it one hour. If I see it is possible I continue if not, I move to the next issue.

**Comment by kiranetph** [comment]
Maybe an onchange can trigger a JS show/hide affecting fields, which can be identified by their id. 
In the xml an additional field parameter like "conditional" holds the ids (list of field names) of affected parameter fields.

**Comment by kiranetph** [comment]
as of the moment, i can think of 2 places ... a yes/no radio button and the select field where "no one" would be the selection criteria --> disable parameter

It would also be used in template parameters like "Show icons" etc ...

**Comment by Serhioromano** [comment]
Success. I could do that less than an hour. Now I need a list of all parameters that could be conditional.

**Comment by kiranetph** [comment]
YEHEY !!!! 
I will try to compile a list here under this issue.

**Comment by kiranetph** [comment]
Section parameter:
How to handle the Feeds & Syndication section since there are 2 modes (RSS/Atom)?
- Personalisation YES/NO will affect  the "General" group. - Is the parameter "Author name as" used outside of personalisation feature? If yes, it should be moved somewhere else ... 

Emerald VIP - Who can see - No one will disable parameters below

User category "Who can submit category" will disable parameters below -- how does the "who can enter meta" work?

**Comment by kiranetph** [comment]
Type parameter:
Properties: Prolong will affect days of prolong. "Author can hide" should be before "Author can prolong"

Tags: Disable all if "Who can view tags" is "no one", also remove and add should be "no one" and all parameters hidden. No sense to add if "no one" can see.

Article title: "composite title mask" only shows when "composite title" is selected

Rating: see up --- rating "no one" all hidden. "enable multiple rating" will influence below parameters 

Category behaviour - Who can select will influence whole block. Multiple category select --> number of categories

Just noticed that you had already conditional parameter in the "Comment" selection ... I never used comments.

Audit log should be first block .. If no all events will be hidden. Event date format under audit log and custom date should only show if custom date is selected

Version control yes will enable maximum number

**Comment by pepperstreet** [comment]
@Serhioromano 
Cool! Glad to hear you've found a solution. Although you can't use the J! core field option for conditional display.  

**Gallery field** would really benefit from it.

**Comment by Serhioromano** [comment]
@pepperstreet 
I am using jQuery for that.

**Comment by kiranetph** [comment]
Section:
Out of aesthetic reasons, the group with ID, Section name, etc should also have a header title. It would look more aligned with properties.

Section home: Show records at section homepage = "Do not show anything" --> hide the 2 parameter
If atom & RSS are No --> don't display fields

for the template section i would suggest to rearrange parameter to a top-down list:
1) markup
2) category index
3) record list
4) default record list
5) compare

on personalisation tab:
user category = no one --> hide rest of parameters

Question on Emerald group: Should it only be displayed when emerald is installed or should it be used as marketing tool to make user aware of emerald. For newbies, a hint to emerald might be helpful.

**Comment by kiranetph** [comment]
Section:
The emerald section should be in its own tab, like in TYPES

**Comment by kiranetph** [comment]
**Types:**
The tabs should be renamed to win some space --> remove the word parameters from the tabs (General Parameters -> General) ... also in Sections.
Group header title for ID, section name, etc would look nice.

Properties:
move author can hide above author can prolong and prolong for x days will be shown only if author can prolong

General:
Article title: "Number of characters" should not be affected by composite conditional.
Rating: "Enable multiple rating" = NO--> hide the multiple rating parameters

Submission behaviour:
Who can submit = "No one" -> hide whole group

Audit trail
custom date format should only show if custom date is selected in event date format

**Comment by Serhioromano** [comment]
How audit log looks now. Very simple. 

![F31E28C7-C33B-40A6-AECE-715C29817F0D](https://user-images.githubusercontent.com/650741/63851049-45472780-c9b7-11e9-904a-3738b14d657d.GIF)

I have finished codding the system, how I go through all parameters and set which one depends on which.
