### ISSUE TITLE
Error You are not authorised to view this resource.

### ISSUE THREAD

**Issue by KEZEO** [Serhioromano/cobalt-9#130]
Hello
with a fresh installation of joomla and the new cobalt 9 beta, when i click on "START WITH COBALT" i have this error on the front end "
_Error
You are not authorised to view this resource._
thank you

**Comment by kiranetph** [comment]
You have to log in into the front end since the default link to the control panel is for "Super User".

**Comment by KEZEO** [comment]
thank you
