### ISSUE TITLE
[9.78] TYPE - Filter by field type

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#131]
Clicking on a "field type" to filter will redirect you to the Control Panel.

TYPE --> Fields --> Field type filter

**Comment by Serhioromano** [comment]
I cannot reproduce but I made some changes to the filtering system. It shows a close button only if the search filter is applied. Now it will show on any filter and reset all filters.

I close it, and after a new release reopen it if there will be an issue again.
