### ISSUE TITLE
Database table design - record_values

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#14]
It might be a good time now to clean up some old obsolete inheritances from the past.
We should open an extra issues per table.
Btw, how can we assign labels to issues?

For a start:
Do we need category_id and params in #__js_res_record_values?

Columns for discussion:
- [x] `category_id` removed in 9.17
- [ ] `params`
- [ ] `field_label`
- [ ] `type_id`
- [x] `section_id` needed for counting multi-type filter number
- [ ] `field_type`
- [ ] `user_id`
- [x] `value_num`

**Comment by Serhioromano** [comment]
> Do we need category_id and params in #__js_res_record_values?

Absolutely not.

**Comment by kiranetph** [comment]
How about the "field_label" ... if we change the field label in the field definition, this column does not get updated also. Is there a function/use case in Cobalt which uses this column?

Then type_id and section_id... needed? We normally come from the #__js_res_record and get all related values through the respective record_id.

field_type?

**Comment by Serhioromano** [comment]
`type_id`, `section_id` and `field_type` are needed for filters. This table is used not to get record values but generally to filter records based on field value.

Right now I believe only ID and key are used to filter. May be also section to limit down amount of rows. 

But in future I was pluning to use those for analytics. That could be useful but maybe not. Right now I believe those could be safely deleted.

**Comment by kiranetph** [comment]
To filter you will only need `field_id`, `field_key` and `field_value`.

You have 2 scenarios: Multi-Type and Single-Type.
For Mult-Type you need to use `field_key` and for Single-Type it should be `field_id`.

`section_id` will be of no help for Multi-Type and will not make a difference for Single-Type.

How about `params`, `user_id` and `value_num`?

**Comment by Serhioromano** [comment]
`value_num` is needed. not used but planned for field that possible to replicate right on form.

Other fields might be deleted since those are not used. But It is index table and I though more we have there the better. Let me go through the code and see if those fields are used.

**Comment by Serhioromano** [comment]
I've checked. I can delete almost all of those fields. But I cannot do it right now since my cobalt 9 and cobalt 8 are configured to the same DB. That will take time.

Do you really think we will seriously make this table smaller?

**Comment by kiranetph** [comment]
No rush. I was just thinking it would be a good time now to clean up things....
The space gain will be between 10 and 20%, i guess (depending on the field_value content.
In my case I have ~750k records occupying ~110MB. I will do another installation and delete the fields there to see.
We can just leave the issue open in the meantime. I will also think, if additional information might be useful.

**Comment by Serhioromano** [comment]
If you delete some fields, edit or add articles will not work. But you can see if it become faster. To restore DB just install Cobalt over. It will detect all missing fields and restore.

**Comment by kiranetph** [comment]
will check today and report here ... it will not really be faster, but smaller. this might have a small memory impact, when you query full records ... but for me the main concern is clean up and now seems to be the right time to do it, since it affects some code changes  see -->  @pepperstreet in his relation field comment

**Comment by kiranetph** [comment]
Before modifications:
112.8 MB (713K rows)
After removing the fields (also removing section_id from index):
88.2MB
Space gain ~ 22% 

But more important, i experienced an error message from the default setting of the ctime in MySQL 5.7 with MySQL setting NO_ZERO_DATE. This might affect future conversions/alter table queries. Will open an extra issue for it.

**Comment by kiranetph** [comment]
`section_id` is needed for multi-type filter count to make sure no other records with same label will be counted.

**Comment by Serhioromano** [comment]
I believe we've deleted all we can here. Other values helps to filter records.
