### ISSUE TITLE
API broken?

### ISSUE THREAD

**Issue by jimiero** [Serhioromano/cobalt-9#140]
Seems that this code is not working anymore:

       <?php $getre =ItemsStore::getRecord($record->id); ?>
        <?php $geti = $model->_prepareItem($getre, 'list'); ?>

It throws this error:

Call to a member function _prepareItem() on boolean

**Comment by Serhioromano** [comment]
How to you get $model? This is how you have to get your model.

```php
MModelBase::addIncludePath(JPATH_ROOT . '/components/com_cobalt/models', 'CobaltModel');
$model = MModelBase::getInstance('Record', 'CobaltModel');
```

**Comment by jimiero** [comment]
Thanks, that helped!
