### ISSUE TITLE
improve sef / seo

### ISSUE THREAD

**Issue by KEZEO** [Serhioromano/cobalt-9#146]
i think it is time to improve sef (it is a part of the work in joomla 4 ) like removing id in url etc
or you can make a little integration for SH404SEF
Best regards and thank you for everything

**Comment by jimiero** [comment]
@KEZEO I have already shared a sh404sef I created for Cobalt

http://www.mintjoomla.com/community/depot/item/2-cobalt-integrations/4156-sh404sef-plugin-1-0-beta.html

You can download and modify it for your needs.

What would be good is if @Serhioromano can add urls for applied filters in Cobalt, that would give Cobalt so good Steroids :)

**Comment by Serhioromano** [comment]
It is not a time for integrations. It is time for improvement Cobalt core. Although SEF is important, I am sorry I decline.
