### ISSUE TITLE
Fatal error: Class 'MModelAdmin' not found

### ISSUE THREAD

**Issue by drinkmaker** [Serhioromano/cobalt-9#19]
Hello,

So we have latest Joomla! 3.4.8 and Cobalt 9.15
One Section and simple Type with 1 text field with default settings.
When we try submit new record http://cobalt9.alexander.khmelnitskiy.ua/themes.html 
We get Fatal Error:
![Fatal error: Class 'MModelAdmin' not found](http://www.googledrive.com/host/0Bxtm5PidFyMoS3gxS0xnb1l4TE0)

What am I doing wrong?

**Comment by Serhioromano** [comment]
Did you install media pack? What template are you using?

Anyway I have added fix. Will make new release later today.

**Comment by drinkmaker** [comment]
Yes, I install media pack pkg_mint.j3.media.v.9.2.
By the way, he wrote the wrong version https://drive.google.com/file/d/0Bxtm5PidFyMoZEFBMXAwZy1iQmM/

I use default Master_2 theme by YooTheme.

Ok. Thank you.
