### ISSUE TITLE
Copy of the section Each time when save.

### ISSUE THREAD

**Issue by drinkmaker** [Serhioromano/cobalt-9#20]
Hello
New problem:
![Many copyes of sections](http://www.googledrive.com/host/0Bxtm5PidFyMoaklBalZfY2x6ZHM)
![Many copyes of sections](http://www.googledrive.com/host/0Bxtm5PidFyMoNGVSNTBUbV9VemM)

**Comment by Serhioromano** [comment]
I am aware of this. Turn of SEF for now. I will try to fix it with next update.

**Comment by Serhioromano** [comment]
FIxed. Close #29.
