### ISSUE TITLE
Menu - MenuItem type - List - Error 500

### ISSUE THREAD

**Issue by pepperstreet** [Serhioromano/cobalt-9#23]
I can't create a **List** menuItem type? 

_"An error has occurred.
500 JHtml cobalt not found."_

Fresh Joomla 3.4.8 + Cobalt 9.17

**Comment by kiranetph** [comment]
Hmmm ... i can create a a new menu item here. :confused: 
I tried it with an existing V8 installation upgraded to V9.17 and a fresh installation (9.11->9.13->9.17)

**Comment by pepperstreet** [comment]
Fresh Joomla 3.4.8 + Cobalt 9.17 
:hushed: :confused:

**Comment by kiranetph** [comment]
Media Pack installed? it is under 9.15

**Comment by pepperstreet** [comment]
Used this separate installer package 
pkg_mint.j3.media.v.9.2.zip

**Comment by Xtream84** [comment]
In my case, problem was with Cobalt - Module - Filters. When I unpublished it, my list section start working without error 500. Module Filters looks like broken, because in admin settings no style and buttons save/cancel.

Joomla! 3.4.8 / Cobalt 9.17 / upgrade from Cobalt 8.681 / mod_filters 8.52

**Comment by pepperstreet** [comment]
Did another fresh test installation on **free 90-day SiteGround environment**. 
Over there the list menuItem type works!

**Comment by pepperstreet** [comment]
Why _closed_? Only 1 additional demo on Siteground worked for me.
I am not 100% sure why it did not work on my local system.

**Update**:
On my existing 9.17 installation... I have re-installed from Cobalt 9.10 -> 9.11 -> 9.15 -> 9.17 
I had two SQL messages regarding Categories/IDs or something like that...
Finally, the list menu-item does also work! So far no error message about "missing Cobalt". :)
So something in the multiple installation steps seemed to fix it. (but which and what?)
