### ISSUE TITLE
Field Group - Toolbar buttons not working - core.js

### ISSUE THREAD

**Issue by pepperstreet** [Serhioromano/cobalt-9#24]
Apparently an old JavaScript issue is back again ;) 
I can't use any of the toolbar buttons in **field group** form.  

_"TypeError: null is not an object (evaluating 'n.task')"_

_../media/system/js/**core.js**_

**Comment by kiranetph** [comment]
same here --> buttons Apply, Save, Cancel in form of field group do not work

**Comment by Serhioromano** [comment]
Fixed.
