### ISSUE TITLE
Control Panel - Listings - manual sorting order by Drag & Drop

### ISSUE THREAD

**Issue by pepperstreet** [Serhioromano/cobalt-9#25]
For the sake of consistency and better overview: 
Listings should have the J! core **Drag & Drop** feature to create a manual sorting order.
Currently **Sections** and **Types** lack this feature. 
Cobalt v9.**17**

**Comment by kiranetph** [comment]
Especially for fields, since the field order is important for intro/full/submission field positioning.
Mandatory feature.

**Comment by pepperstreet** [comment]
As far as I can see, **Fields** already have Drag&Drop.
(Cobalt 9.**17**)

**Comment by Serhioromano** [comment]
> Currently Sections and Types lack this feature.

@pepperstreet  Why do you need to manually order sections or types? There is an ordering option for fields and categories, that makes sense, but why order types?
