### ISSUE TITLE
Country tables

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#26]
A new installation of C9 Beta/media pack will create an empty table `#__js_res_ip_2_country`. Is the content missing or is it not used anymore?

An updated installation has the `#__js_res_ip_2_country` table with 91K records and also a `#__js_res_country` and an additional `#__js_res_ip_2_countries` table with slightly different structure. Are both needed?

**Comment by Serhioromano** [comment]
> A new installation of C9 Beta/media pack will create an empty table #__js_res_ip_2_country. Is the content missing or is it not used anymore?

It will install countries on update or second install

**Comment by Serhioromano** [comment]
> Are both needed?

Yes. Country table is used by GEO field too.
