### ISSUE TITLE
Cancel creating field problem

### ISSUE THREAD

**Issue by Giorgi625** [Serhioromano/cobalt-9#27]
When I decide to not to create new field and press cancel I get this and can't return to field list page
![field-cancel](https://cloud.githubusercontent.com/assets/16633699/12351689/f630cd5c-bb98-11e5-95cd-ed1ad3ceb2ac.jpg)

**Comment by andiamine** [comment]
Hi my friend try full screen mode

**Comment by Serhioromano** [comment]
Fixed.
