### ISSUE TITLE
Field - edit and change type of field - 1 checked out field plus 1 new field

### ISSUE THREAD

**Issue by pepperstreet** [Serhioromano/cobalt-9#29]
Sorry, seems to be related to SEF setting described in issue #20 

---

I have created a test **Audio field**. 
Funnily after clicking save, I got **2** fields of this type. 
One of them is still _checked-out_. 
Therefore I had to _check-in_ the field by clicking the **lock icon**. 
Then I wanted to change the type of the second Audio field to a **different type**... 
The result is again one _checked-out_ audio field and a second **new** field!?

![bildschirmfoto 2016-01-16 um 22 54 38](https://cloud.githubusercontent.com/assets/1189521/12374756/5c121258-bca6-11e5-9ecd-69d150d067d9.png)

Another test with a **checkbox** field... changed to a **Radio** field: 
![bildschirmfoto 2016-01-16 um 23 15 08](https://cloud.githubusercontent.com/assets/1189521/12374778/2461627c-bca7-11e5-9718-58e128e09d78.png)

**Comment by pepperstreet** [comment]
Now it's getting weird! Every SAVE operation, even in section, seem to produce **checked-out** COPIES !? 
![bildschirmfoto 2016-01-16 um 23 17 58](https://cloud.githubusercontent.com/assets/1189521/12374801/de9bdcc6-bca7-11e5-8455-df661f42a051.png)

This happens on a fresh Joomla 3.4.8 demo install on the **free 90-day SiteGround environment**. 
Cobalt 9.17 & latest Media Package.

![bildschirmfoto 2016-01-16 um 23 24 19](https://cloud.githubusercontent.com/assets/1189521/12374813/58059412-bca8-11e5-9471-22425c23e291.png)

**Comment by Serhioromano** [comment]
Turn off SEF for now. I am still working on this one.
