### ISSUE TITLE
V9.11 - TYPE in dashboard not working

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#3]
![2016-01-10_20-55-15](https://cloud.githubusercontent.com/assets/15226809/12221587/9f75acb8-b7dc-11e5-91db-d2369225580d.png)

http://test.local/report/index.php?option=com_cobalt&view=ctype&Itemid=106

**Comment by Serhioromano** [comment]
Use types link in menu right now. There is mistake in dashboard link.
