### ISSUE TITLE
Full screen css issues

### ISSUE THREAD

**Issue by andiamine** [Serhioromano/cobalt-9#33]
Hi , first issues , css bugs:

this additional css code will fix problem:

body{
 padding: 15px;
}
/\* fix icons in list */
ul.cpanel-list li a{
    padding-left: 20px;
    background-size: 20px 20px;
    background-repeat: no-repeat;
    display: block;
    margin-bottom: 5px;
}

**Comment by pepperstreet** [comment]
As far as I can see, there are more issues with the current "fullscreen" option in global config.  
At least in my tests, it seems to miss the necessary bootstrap files. for instance: Toggle checkboxes are not displayed. In general, the fullscreen display mode feels strange to me. If this is a 80/85% modal window with shadow, it would feel more familiar... 
(going to open some related issues/topics)

![bildschirmfoto 2016-01-13 um 19 22 24](https://cloud.githubusercontent.com/assets/1189521/12378930/f22a45f6-bd4d-11e5-9c22-913903d2465e.png)

**Comment by kiranetph** [comment]
I would not suggest to use or even implement a "full screen" modus. 
Beside the already mentioned issues (no main navigation, missing module positions, etc) other problems will come along the way ... this mode was mainly made for printing the component content.

The existing dashboard ( i would even prefer "Control Panel") should just be improved a little to work with existing templates/frameworks. We should start with the "Control Panel" landing page, then work on each of the sub menues.

**Comment by Serhioromano** [comment]
I agree with @kiranetph. I already regret that added fullscreen mode. Unfortunately component.php file is not always support head scripts load and other things. You never know if it is going to work or not.

**Comment by kiranetph** [comment]
lets remove the "full screen" mode, to avoid more issues ... we better work on the control panel .
I will open some issues on it later. 
btw, the prefix mode is ok, but should automatically load css files with same name. I would also suggest to allow access to xml configuration to change parameter (like in list, markup etc templates) --> icon, color , number of records ... i will submit a demo control panel, after making tests with different frameworks

**Comment by Barabashk** [comment]
it's interesting for me why team decide use front-end editing, the admin view is almost perfect now in C8 and people are used to it. but now must be done a lot of work to good stable work at least. 
We editing admin setting once and later works only with articles

and what about security? admin panel have many security levels, but to edit cobalt main params from front-end i must know only login and pass of admin

also 1 more step is needed to start work with cobalt - creating admin-menu-item. it make me sad a little. I think less steps is a better way

**Comment by pepperstreet** [comment]
@Serhioromano You don't have to use the default component.php 
It could be your own file and naming. Then you can add any required CSS/JS stuff.

**Comment by kiranetph** [comment]
> it's interesting for me why team decide use front-end editing,

@Barabashk Not sure, but It might be part of a long term strategy to transform Cobalt from a "Joomla only" component to a universal application which can be used with other CMS.
See gantry5 --> works with Joomla, Wordpress, Grav, Stand-alone ...

**Comment by pepperstreet** [comment]
## Build-in fullscreen alternative - Protostar Fluid :)

Actually, it is quite simple to get a cross-css-framework compatibility with a J! core feature:
- Assign default **Protostar** template to Cobalt CPanel menuItem,  
- Either change Protostar template parameter to "**fluid**" 
- Or create a **template style** and set the parameter there 

#### Nice side-effects
- Full BSv2 support. Cobalt admin/config can stay on JUI/Bootstrap v2
- all Protostar Module-Positions can be utilized for a "personal custom dashboard"

#### Eye-candy & branding ;)
- set base color to #0047ab Cobalt blue
- same for Emerald #50c878 green

**Comment by justanotherguyme** [comment]
Full screen is needed. Without you cannot access management of fields. As the menu extents pass my template so it is not select-able. You can see it but when you cross the gap to try and click the drop down menu disappears.
![cbbug](https://cloud.githubusercontent.com/assets/8334247/13515070/5b6c1542-e17c-11e5-8b8d-00d593240eb9.png)

**Comment by justanotherguyme** [comment]
If full screen isn't an option we should at least set a minimum height in CO9 Dashboard. I like full screen as I deal with many many many many fields.
