### ISSUE TITLE
Uploads field wrong file path for uploaded files

### ISSUE THREAD

**Issue by jimmrom** [Serhioromano/cobalt-9#39]
When you create an uploads field the uploaded files get a wrong file path:

http://www.domain.com/http://www.domain.com//uploads/uploads/2016-01/1453210472_07398d8aba8e0b705748b3657d6948b5.jpg

You see it has double domain name

**Comment by Serhioromano** [comment]
Upload field is refactored. There is new parameter now. One can select betwin mootool and flow now.

![2019-08-25_19-56-54](https://user-images.githubusercontent.com/650741/63650987-87cbf280-c772-11e9-8a87-cf2344973db5.jpg)
