### ISSUE TITLE
Error: 403 CCANNOTACCESSADMINAREA

### ISSUE THREAD

**Issue by Giorgi625** [Serhioromano/cobalt-9#4]
So i installed Cobalt using files in Releases on Clean Joomla 3.4.8 and on Site where I had Cobalt 8 installed. in both I have on admin only about and configuration pages. so I created admin dashboard item in menu and when I access to this page on frontend 
![1](https://cloud.githubusercontent.com/assets/16633699/12222359/a1a7f936-b7d3-11e5-8e71-04aa4f91a126.jpg)
when I try to go to any link from this page I am redirected to Error page with status:
403 CCANNOTACCESSADMINAREA
1	JApplicationCms->execute()	index.php:45
2	JApplicationSite->doExecute()	libraries/cms/application/cms.php:252
3	JApplicationSite->dispatch()	libraries/cms/application/site.php:230
4	JComponentHelper::renderComponent()	libraries/cms/application/site.php:191
5	JComponentHelper::executeComponent() libraries/cms/component/helper.php:372
6	require_once()	libraries/cms/component/helper.php:392
7	MControllerBase->execute()	components/com_cobalt/cobalt.php:25
8	CobaltController->display()	libraries/mint/mvc/controller/base.php:722
9	JError::raiseError()	components/com_cobalt/controller.php:27
10	JError::raise()	libraries/legacy/error/error.php:254

**Comment by Giorgi625** [comment]
It seams I forgot to set user for global moderator, now it works

**Comment by Giorgi625** [comment]
This is not problem but it would be better if when you rise width of description area, navigation pannels width would not decrease.
![Uploading 2.jpg…]()

**Comment by Giorgi625** [comment]
This is not problem but it would be better if when you rise width of description area, navigation pannels width would not decrease.
![2](https://cloud.githubusercontent.com/assets/16633699/12222880/ba2e7fc6-b7e1-11e5-889a-0d1ada0d5432.jpg)

**Comment by Giorgi625** [comment]
Second Issue when I edit Type id does not change current type but creates another copy of edited type.
When I am editing Type1, for example rename it as Type2 and press save I get Type1 and Type2 also

**Comment by andiamine** [comment]
i suggest to auto find superadmin user and assign it as global moderator , so will help beginner users.

**Comment by andiamine** [comment]
also dashboard should redirect to homepage or show 403 if user not global moderator or not logged.

**Comment by andiamine** [comment]
also auto add menu item for dashboard when cobalt 9 installed (for new installations only)

**Comment by Serhioromano** [comment]
@Giorgi625 
> Second Issue when I edit Type id does not change current type but creates another copy of edited type.
When I am editing Type1, for example rename it as Type2 and press save I get Type1 and Type2 also

This one looks like SEF issue. For now turn SEF off to edit type. I'll check what could be the reason.

@andiamine 
> i suggest to auto find superadmin user and assign it as global moderator , so will help beginner users.

Please all your suggestions create separate topic so it could be discussed, accepted or rejected. It is hard to use issue tracker like a chat.

@Giorgi625 
Looks like you also forgot to install media pack.

**Comment by Giorgi625** [comment]
No I always install media pack first and then cobalt. but from skype you shared mediapack 8.86, here is 8.80, so which is better to install?

**Comment by Serhioromano** [comment]
8.86 is better.
