### ISSUE TITLE
Sort Order and Sort By in Control Panel 

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#43]
For discussion:

Should the `sort order` and `sort by` controls on the SECTION, CATEGORIES, TYPES, FIELDS, VOTES, COMMENTS and TAGS be removed?

For me it is easier to click the table header rather to select from the dropdown. 
My opinion: The controls are redundant and can be removed.
![2016-01-21_13-02-29](https://cloud.githubusercontent.com/assets/15226809/12472186/6ee3020a-c040-11e5-99eb-f05a50266fa6.png)

**Comment by Serhioromano** [comment]
Not all sortable fields are actual columns. At least for records. 

The question is how destructive those parameters are? So they stay in a way?
