### ISSUE TITLE
Error CUPLOADREQ

### ISSUE THREAD

**Issue by scenium15** [Serhioromano/cobalt-9#47]
After installing and switching settings, an error: CUPLOADREQ
![cuploadreq](https://cloud.githubusercontent.com/assets/16851324/12529945/49a29078-c1d5-11e5-9b38-8c0cdfddd0ae.jpg)

**Comment by matijaveber** [comment]
Confirming

**Comment by Serhioromano** [comment]
fixed

**Comment by scenium15** [comment]
Более трех лет прошло и лед тронулся)
Сергей, сообщи (можно на официальном сайте), какие планы на Cobalt 9 и 10?
В течении полугода обещают стабильную версию Joomla 4. Под неё разрабатывается Cobalt?

**Comment by Serhioromano** [comment]
> Под неё разрабатывается Cobalt?

Пока не на этой платформе на J3. Если сделаю быстрей чем выйдет J4 то выпущу на 3, если сделаю к 4ке, выпущу уже на 4ку. Но работать будет и на 3йке. План такой.
