### ISSUE TITLE
Gallery field - wrong image path for uploaded images

### ISSUE THREAD

**Issue by scenium15** [Serhioromano/cobalt-9#48]
When you create an gallery field the uploaded images get a wrong file path:

http://domain.com/http://domain.com//uploads/gallery/2016-01/1453555447_0a45ac3916fd07d460a4e8b8a63b4825.jpg

Also in the "Gallery" default two uploaded file. 
![gallery](https://cloud.githubusercontent.com/assets/16851324/12530389/c7cd82b2-c1e6-11e5-9e1f-5be8b939a891.jpg)

**Comment by kiranetph** [comment]
same as #39

**Comment by Serhioromano** [comment]
Gallery field as all uploads fields are refactored to use Flow library to create UI.
