### ISSUE TITLE
Warning and fatal error when filter module enabled

### ISSUE THREAD

**Issue by danielbidala** [Serhioromano/cobalt-9#5]
Update from Cobalt 8 (media pack v8.80 & cobalt v9.11). Filter module is enabled. On frontend I get this error when try to navigate admin dashboard.

Warning: Creating default object from empty value in /srv/users/kalilab/ugyvitel-develop/modules/mod_cobalt_filters/mod_cobalt_filters.php on line 53

Fatal error: Call to undefined method stdClass::getFilters() in /srv/users/kalilab/ugyvitel-develop/modules/mod_cobalt_filters/mod_cobalt_filters.php on line 55

**Comment by Serhioromano** [comment]
Fixed in next release.
