### ISSUE TITLE
Module Filters  and Module Records - error

### ISSUE THREAD

**Issue by scenium15** [Serhioromano/cobalt-9#50]
If the administrative part of the switch to configure the module Filters and module Records, get on the white page with incorrect font (something encoded).
![filters](https://cloud.githubusercontent.com/assets/16851324/12535000/b04b283e-c27b-11e5-8a37-a29a1accb902.jpg)
![records](https://cloud.githubusercontent.com/assets/16851324/12535064/d3c93f82-c27e-11e5-9be0-28cd13b99e7d.jpg)

**Comment by Serhioromano** [comment]
In order to get error, you have to enable debug mode and error reporting to maximum in global Joomla config. Then refresh this page. If you do not see error, look into page source.

**Comment by Serhioromano** [comment]
I could reproduce it. Fixed.
