### ISSUE TITLE
500 JHtml cobalt not found

### ISSUE THREAD

**Issue by matijaveber** [Serhioromano/cobalt-9#51]
1. create section
2. create menu item
3. select cobalt->list

Whe I select list records menu item I get 500 JHtml cobalt not found.

This happens when I install Cobalt9 for the first time. When I install it over with the same version again it's working fine. This happened locally and on hosting.

**Comment by pepperstreet** [comment]
#23 Confirmed. 
Had the same issue on fresh install. (v9.**17**)
I had to re-install previous versions over, then latest version again.

**Comment by Serhioromano** [comment]
I cannot reproduce. Could you enable debug mode and error reporting to full. There should be error stack. Post it here.
