### ISSUE TITLE
Template php edit and mod_security

### ISSUE THREAD

**Issue by matijaveber** [Serhioromano/cobalt-9#52]
With mod_security enabled you can't edit php files of templates in frontend. If this can't be fixed then I suggest topltip for clarification.

**Comment by Serhioromano** [comment]
@matijaveber What is mod_security? Is it third party module?

**Comment by matijaveber** [comment]
It's apache module.It's web application firewall. I guess it is third party module [Website](https://modsecurity.org/)

**Comment by Serhioromano** [comment]
I see. It is Apache module not Joomla's.

I cannot install mod_security to my mac because I have custom Apache installationa тв I found only instruction how to install it with `port`. 

Can you describe the problem?

**Comment by kiranetph** [comment]
https://gist.github.com/amarnus/621fc1612036e186b6a6

**Comment by pepperstreet** [comment]
Joomla core has backend edit features for a long time. Never had or heard about any issues... 
Does Cobalt use a different technique? If so, why not utilize the core features? 

BTW, would be nice to quick-edit field templates, too. ;)

**Comment by Serhioromano** [comment]
@kiranetph brew also give an error.
