### ISSUE TITLE
Can't select moderator

### ISSUE THREAD

**Issue by matijaveber** [Serhioromano/cobalt-9#53]
When I want to assign moderator to section I get 404 error in modal when I click select button.

Also when saving moderator (one is preselected) it redirects to homepage. This acctually doesn't save this preselected moderator.

![add new moderator select](https://cloud.githubusercontent.com/assets/6883519/12548859/9006eb24-c359-11e5-94db-c1d60b54e212.png)

**Comment by Serhioromano** [comment]
FIxed.
