### ISSUE TITLE
Media Pack file size

### ISSUE THREAD

**Issue by matijaveber** [Serhioromano/cobalt-9#55]
Is it possible to create media pack smaller than 2MB? On some hostings you have limit upload file size of 2MB and with novice users using Cobalt you will have unnecessary forum posts. Or if user could install media pack with click after installing Cobalt. Like Joomla has install from web.

**Comment by Serhioromano** [comment]
I'll try to optimize it later prior to release.

**Comment by kiranetph** [comment]
Most of the popular extensions are bigger than 2MB. Akeeba Backup, Community Builder, Jomsocial, Easy Social, etc ... 
Anyway, the 2MB limit might still be good to observe...
