### ISSUE TITLE
Tags - Bootstrap Tags project

### ISSUE THREAD

**Issue by pepperstreet** [Serhioromano/cobalt-9#57]
Hello Sergey, do you still have plans to utilize your "Bootstrap Tags" project? 
https://github.com/Serhioromano/bootstrap-tags

Or are there any other scripts and options for Tags input in Cobalt 9? 
Maybe something that is shared in other fields? i.e. Auto-Complete/Suggest based on jQuery

**Comment by Serhioromano** [comment]
This would be a nice moment for that. Actually this is what i have developed this for. It has all features of autocomplete and some more. Let's see if I can do it.

**Comment by pepperstreet** [comment]
Maybe too much relations to a certain Bootstrap version? Or is it quite universal? 
(just thinking loud)

**Comment by Serhioromano** [comment]
> Or is it quite universal? 

It doesn't depends on Bootstrap as JS. It only depends on Bootstrap as CSS. SO it is easily adjustable.

**Comment by Serhioromano** [comment]
Changed all to this new library,
