### ISSUE TITLE
MySQL NO_ZERO_DATE issue under default MySQL 5.7.x

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#59]
When trying to remove column from #__js_res_record_values under phpMyAdmin (4.5.3.1) and MySQL 5.7.10, I received an error #1067 - Invalid default value for 'ctime' (0000-00-00 00:00:00).
This is based on the default NO_ZERO_DATE setting from MySQL 5.7.x
To change columns i changed the default to "1000-01-01 00:00:00" to allow "alter" the table. Since ctime will always have a content, it might be a good idea to change the default value to avoid future problems.

**Comment by Serhioromano** [comment]
Done.
