### ISSUE TITLE
Fatal error when try to add New Field

### ISSUE THREAD

**Issue by danielbidala** [Serhioromano/cobalt-9#6]
Update from Cobalt 8 (media pack v8.80 & cobalt v9.11).

Fatal error: Call to a member function getFields() on a non-object in /srv/users/kalilab/ugyvitel-develop/administrator/components/com_cobalt/library/php/html/cobalt.php on line 99

**Comment by Serhioromano** [comment]
there is no cush a file already `/administrator/components/com_cobalt/library/php/html/cobalt.php`. Do you have error stack?

**Comment by danielbidala** [comment]
I get this same error when I try to edit existing field. What do you mean under error stack?

**Comment by danielbidala** [comment]
![image](https://cloud.githubusercontent.com/assets/16636699/12235757/1f001182-b876-11e5-96f3-d722035b15ba.png)

**Comment by danielbidala** [comment]
![image](https://cloud.githubusercontent.com/assets/16636699/12235791/4c24a830-b876-11e5-87fd-e4587c6c3829.png)

**Comment by danielbidala** [comment]
Ok, with v9.13 this problem is solved!
