### ISSUE TITLE
Template compatibility

### ISSUE THREAD

**Issue by gerrobb** [Serhioromano/cobalt-9#63]
In my experience, Cobalt has been difficult to properly configure under the best of circumstances. Add to this a problem template and the difficulty level goes up significantly. It would be beneficial if in addition to a template compatibility button, you were to include a test to determine where the compatibility issues lie. It would help to determine what the user needs to turn off to make Cobalt work properly. For example, I have been using the Gantry framework and while most of the functions work, often the yes/no buttons do not display properly. But by assigning Protostar to dashboard and submit in cobalt, I am able to use this feature. 

It might also be beneficial to have a few different template compatibility buttons. That way, one could notch out the features that cause problems and others that aren't causing problems. Perhaps this feature could be tied to the above suggested compatibility test?

**Comment by Serhioromano** [comment]
Compatibility is not, what to exclude but what to include. It simply includes jquery and bootstrap to ensure all features work.
