### ISSUE TITLE
Home page menü

### ISSUE THREAD

**Issue by mekamak** [Serhioromano/cobalt-9#65]
![cobalt](https://cloud.githubusercontent.com/assets/12696950/13195740/6aac544a-d7c2-11e5-9d77-cb72fdc8aa1f.jpg)

**Comment by justanotherguyme** [comment]
I think the homepage link should be on the right  - It would match where joomla places the homepage link in the back end!

![homepagelink](https://cloud.githubusercontent.com/assets/8334247/13514641/a39cecb4-e178-11e5-8da1-a8e80023ec01.jpg)

**Comment by Serhioromano** [comment]
What means homepage? Control panel? The Cobalt9 logo is a link to homepage.
