### ISSUE TITLE
Remove JW player

### ISSUE THREAD

**Issue by justanotherguyme** [Serhioromano/cobalt-9#67]
Hi Sergey - HTML5 supports audio and video by default so we should really consider removing the JW Player from CO9. Its a great player (prob the best) But it cant be used on commercial sites with out cost and its too expensive. We spoke April 2014 about switching to mediaelement.js since this has flash fallback but since then flash has died and a player may not be needed at all since HTML 5 now supportsthe audio and video funstion. Please reference this link: 

http://www.mintjoomla.com/support/community-forum/item/48-cobalt-8/1593-audio-field-audio-does-not-play-in-list.html 

I hope you consider..

**Comment by kiranetph** [comment]
Since the video field is a commercial field, I would suggest to make a new VIDEO2 field to keep compatibility (player) of existing installations.

**Comment by justanotherguyme** [comment]
What do you mean the video is a commercial field?

**Comment by kiranetph** [comment]
http://www.mintjoomla.com/download/joomla-3/item/21-media-fields/99-field-video.html

The price for the field is 15$. If someone bought it and now the field changes the player, his existing solution will also change. 
Much better to provide a Version 2 of the field (even with new functionality) to keep the existing video field intact.

**Comment by justanotherguyme** [comment]
I see. The Audio upload also includes the payer and suffers the same. More reason to remove the JW player from the component. And since flash is dead I see no reason to forget flash fallback and just use HTML 5 going forward with the builtin audio video tags since CO9 is all new and for the future!

**Comment by KEZEO** [comment]
i think now we could improve video field thank to a new opensource solution like here  :  https://blog.bitsrc.io/5-open-source-html5-video-players-for-2018-38fa85932afb

**Comment by Serhioromano** [comment]
As I introduce fields templates parameters, there might be few output templates with JW and other players.
