### ISSUE TITLE
V9.13 Installation warning on upgrade

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#7]
Warning
JFolder: :delete: Path is not a folder. Path: /administrator/components/com_cobalt/controllers
JFolder: :delete: Path is not a folder. Path: /administrator/components/com_cobalt/helpers
JFolder: :delete: Path is not a folder. Path: /administrator/components/com_cobalt/models
JFolder: :delete: Path is not a folder. Path: /administrator/components/com_cobalt/tables
JFolder: :delete: Path is not a folder. Path: /administrator/components/com_cobalt/xml

**Comment by Serhioromano** [comment]
Yes, those are cleanups. If you already have those deleted you have that warning. I'll add check directory exists.
