### ISSUE TITLE
Добавление модератора в раздел

### ISSUE THREAD

**Issue by github-dima** [Serhioromano/cobalt-9#73]
J 3.5.1
PHP 5.6

![1](https://cloud.githubusercontent.com/assets/18648810/14770886/3d5f5b36-0a7b-11e6-8ec3-6857afa14f34.png)
![2](https://cloud.githubusercontent.com/assets/18648810/14770899/867d1538-0a7b-11e6-8b14-3ff16734302e.png)
![3](https://cloud.githubusercontent.com/assets/18648810/14770892/6bc91d04-0a7b-11e6-81e6-318bc70857ec.png)
![4](https://cloud.githubusercontent.com/assets/18648810/14770893/6fefe20a-0a7b-11e6-9c74-40df559acff8.png)

**Comment by Serhioromano** [comment]
fixed
