### ISSUE TITLE
Auto Choose of global moderator (for new installations)

### ISSUE THREAD

**Issue by andiamine** [Serhioromano/cobalt-9#8]
I think it's better to auto select a super admin as a global moderator for new cobalt 9 installations.

it's just for novice and beginner users, this will help them also you will not get many questions and support about that.

**Comment by kiranetph** [comment]
On a new installation, Cobalt will always redirect to the configuration page first.
The global moderator does not have to be the super admin. Setting the field "Global Moderator" as required, would solve the issue.

**Comment by Serhioromano** [comment]
> Setting the field "Global Moderator" as required, would solve the issue.

In deed. Most simple solution. Done.
