### ISSUE TITLE
Import improvement - Field Text

### ISSUE THREAD

**Issue by kiranetph** [Serhioromano/cobalt-9#85]
Check import content based on field parameter settings
- [x] "Allow Raw HTML" parameter 
- [x] "Unique Value" parameter 
- [x] "Default Value" parameter 
- [x] "Maximum Length" parameter 
- [ ] "Mask Settings" parameter 

Import Parameter:
Empty import field value : -> no value / default value
Unique Value violation: -> no value/.. ?
Maximum Length violation : -> cut import string / no value / default value
Mask setting violation : -> No value / default value

If "unique value" is true, then there can not be any default value
- [ ] Include onImportForm, otherwise it will not show the assigned field for import

**Comment by Serhioromano** [comment]
I was thinking of that.  Not only for the text field. For every field, there might be a lot of different conditions, filters, validators, ... I have no idea how to add such a big set of parameters for every imported field. 

Right now in the improt, I rely on the user. If he wants HTML in the fields, create an import file with HTML If you want default value, create an import file with a default value. If you want to confirm to mask, prepare it that way. This is the only solution I see right now. 

Although I added all listed value treatments except mask as it works only in JS. I cannot use that mask. But there are Regex settings, user can use that to check if value conforms to a regex pattern.
