### ISSUE TITLE
Clicked section->Personalisation->(Yes/No) Caused crash and error on form.

### ISSUE THREAD

**Issue by justanotherguyme** [Serhioromano/cobalt-9#90]
![2016-06-26 15_29_01-admin dashboard](https://cloud.githubusercontent.com/assets/8334247/16364412/41422fde-3bb4-11e6-997f-42ae90821395.png)
![2016-06-26 15_40_07-talent profile](https://cloud.githubusercontent.com/assets/8334247/16364413/4ec83e50-3bb4-11e6-8da9-35b8c1f0b7c5.png)

**Comment by justanotherguyme** [comment]
Error was on form submit page

**Comment by Serhioromano** [comment]
Check section parameter if that type is still selected in parameters.
