### ISSUE TITLE
Sever buttons issues

### ISSUE THREAD

**Issue by justanotherguyme** [Serhioromano/cobalt-9#93]
![2016-06-26 15_15_07-admin dashboard](https://cloud.githubusercontent.com/assets/8334247/16364435/a5c504ea-3bb4-11e6-9ec7-ea5fea9c2fa1.png)

**Comment by justanotherguyme** [comment]
![2016-06-26 15_18_24-submit new talent - talent profile - uppercut audio sound design with punch](https://cloud.githubusercontent.com/assets/8334247/16364438/af6b1818-3bb4-11e6-8228-353c170b4d69.png)

**Comment by matijaveber** [comment]
This is how buttons are in Cobalt. I see no wrong with that. And you can always change style and text for buttons yourself.
