### ISSUE TITLE
Конфликт с  модулем Breadcrumbs

### ISSUE THREAD

**Issue by github-dima** [Serhioromano/cobalt-9#94]
J 3.6  protostar
Модуль Breadcrumbs в стандартной позиции "position-2"
Получаем такое:
![bug-20](https://cloud.githubusercontent.com/assets/18648810/22852825/8859465c-f04d-11e6-8484-3b3bf2c13c6b.jpg)
 Если Breadcrumbs перенести, например, в футер, проблема исчезает.

**Comment by Serhioromano** [comment]
Cannot reproduce. All fine now. May be was a Joomla bug.
