### ISSUE TITLE
v9.18 - Import - Fatal error in view.html.php

### ISSUE THREAD

**Issue by pepperstreet** [Serhioromano/cobalt-9#96]
Hello, since I have issues in latest Cobalt 8 import, I tried my latest (?) v9.18  
Right after CSV upload I wanted to get to the next step. After clicking next I get the following error message:  

Fatal error: Call to undefined method CobaltModelTfields::getFormFields() in /Applications/MAMP/htdocs/cobalt9/components/com_cobalt/views/import/view.html.php on line 96 

The test section and type is a sort of a simple movie/actor database. The CSV file is not specific to the content and relation! Just a simple, basic COMMA separated dummy file.

Any thoughts are much appreciated.

**Comment by kiranetph** [comment]
Pepperstreet,

the "Alpha V9" (V9.18) was not updated publicly for over 1 year.
Only V8 received some import fixes around June/July 2016. Better try your luck with V8.

**Comment by pepperstreet** [comment]
Thanks for your quick reply. 
PS: Did not really expect it to work, but wanted to be sure my CSV file is correct. The main reason I tried v9 were my import issues in current v8.

**Comment by kiranetph** [comment]
You can email me your CSV (2-3 lines only) and i can try it under V8 if you want ... attach it here or email to sack.gesicht@yahoo.com

**Comment by Serhioromano** [comment]
CVS upload is buggy. Not because of the code but because of not unifies CSV standard. Very hadrd to read CSV files although I use PHP standard fgetcsv() function. So I'll recomend to use JSON as primary import file and CSV on your own risk.
