### ISSUE TITLE
Mail field - fixed layout variant breaks page rendering

### ISSUE THREAD

**Issue by pepperstreet** [Serhioromano/cobalt-9#98]
Hello, there is a strange issue with "**fixed**" layout variant. The other two variants seem to work though. As soon as "fixed" is selected, the frontend page does not render its full content. The entire sidebar and the following content below is missing. No following fields, nor a footer area shows up.

![cob_8_9_field_mail_fixed-missing-sidebar-and-fields](https://cloud.githubusercontent.com/assets/1189521/25306522/d56b5bec-278e-11e7-996a-9322de149c1c.png)

**Comment by pepperstreet** [comment]
## Culprit and How to fix it
Default output template has two simple syntax errors. 
An extra _/_ slash had to be removed, and the iframe closing-tag was missing.

See line 70+ in the following file:
_../components/com_cobalt/fields/email/tmpl/output/default.php_

Corrected syntax is:
`<iframe frameborder="0" src="/<?php echo $url_form;?>" width="100%" height="<?php echo $params->get('params.height', 600);?>" ></iframe>`

---

Thanks again to "Jeff" from down-under! ;)

**Comment by Serhioromano** [comment]
I cannot see problems here. I can see all that is ought to be shown.
