### ISSUE TITLE
Frontend only vs. Front- and Backend

### ISSUE THREAD

**Issue by pepperstreet** [Serhioromano/cobalt-9#99]
Hello, just wanted to raise some thoughts about Administration and new features since Joomla 3.7
 
Apparently there is the new "**Session sharing**" which seem to allow backend and frontend login at the same time. Something that I really miss, while Cobalt8 backend Records manager opens in modal window and requires an annoying 2nd login. 
Apart from that, Joomla 3.7 allows custom "**Admin Menus**" incl. ACL settings. So, a total customized backend is possible, too. 

Any chance to re-invent the backend in Cobalt 9 ;)

Any thoughts and opinions are appreciated...

**Comment by Serhioromano** [comment]
Cobalt 9 will be all frontend like Emerald. Everything is already transferred. No way back.
